
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sumudu Lakshan
 */
public class Checkbox extends javax.swing.JFrame {

    /**
     * Creates new form Checkbox
     */
    public Checkbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javacheck = new javax.swing.JCheckBox();
        phpcheck = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        sqlcheck = new javax.swing.JCheckBox();
        jscheck = new javax.swing.JCheckBox();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javacheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        javacheck.setText("java");

        phpcheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phpcheck.setText("php");

        jCheckBox4.setText("jCheckBox1");

        sqlcheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sqlcheck.setText("sql");

        jscheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jscheck.setText("js");
        jscheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jscheckActionPerformed(evt);
            }
        });

        btn.setBackground(new java.awt.Color(255, 255, 153));
        btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn.setText("select");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscheck)
                    .addComponent(phpcheck)
                    .addComponent(javacheck)
                    .addComponent(sqlcheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(btn)
                .addGap(91, 91, 91))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(jCheckBox4)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(javacheck)
                .addGap(18, 18, 18)
                .addComponent(phpcheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sqlcheck)
                .addGap(18, 18, 18)
                .addComponent(jscheck)
                .addGap(14, 14, 14)
                .addComponent(btn)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jscheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jscheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jscheckActionPerformed
        
    
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        String langs= "";
        if(javacheck.isSelected()){
            langs = langs+" java";
        }
        if(phpcheck.isSelected()){
            langs = langs+" php";
        }
        if(sqlcheck.isSelected()){
            langs = langs+" sql";
        }
        if(jscheck.isSelected()){
            langs = langs+" js";
        }
        
        if(langs == ""){
        JOptionPane.showMessageDialog(rootPane, "You have not selected any language");
        }
        else{
        JOptionPane.showMessageDialog(rootPane, "You have selected"+langs+" languages");
        }
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox javacheck;
    private javax.swing.JCheckBox jscheck;
    private javax.swing.JCheckBox phpcheck;
    private javax.swing.JCheckBox sqlcheck;
    // End of variables declaration//GEN-END:variables
}
